#!/usr/bin/env python 
dog_name = input('write dog name:')
dog_shelter = input('write shelter name:')
type_of_dog = input('write type:')
mood = input('write the dogs mood:')
action = input('write action:')
place = input('write a place:')
noun = input('write a noun:')
creatures = input('write a plural noun:')
shelter = input('write a place to hide:')
object = input('write an object:')
weapon = input('write a weapon:')
time = input('write a time:')
adjective = input('write an adjective:')
feeling = input('write a feeling:')
thing = input('write a thing:')
award = input('write a type of award:') 
adj = input('write an adjective:')
status = input('write a status:')


print('The dogs name was' + dog_name + '.')
print('He was in a shelter called' + dog_shelter + 'which was made just for' + type_of_dog + '.')
print('He was very' + mood + '.')
print('The dog did not want to' + action + 'in the shelter' + '.')
print('So he decided to run far away to' + place + '.')
print('He ended up getting lost in a' + noun + 'and he was very scared')
print('In the corner of his eye he saw many' + creatures + 'and they were charging at him in full speed' + ".")
print('He started to run towards the' + shelter + 'to get away from the creatures')
print('Then he saw a' + object + 'and started to climb up' +'.')
print('He stayed up there and he found a' + weapon + 'to defeat them all' + '.')
print('He started to climb back down and he killed them all in' + time + '.')
print('After killing them all he was known as a' + adjective + 'and all the villigers cheered for him' + '.')
print('He was very' + feeling + 'and never wanted to leave go back into the shelter' '.')
print('To the villigers he was a' + thing + '.')
print('He was awarded with a' + award + 'for his bravery' + '.')
print('He was no longer a' + adj + 'dog' + '.')
print('He was a dog of great' + status + '.') 
